In [2]:
import mlrose_hiive as mlrose
import numpy as np
import math
from mlrose_hiive import GeomDecay

tail(b, x) is the number of trailing b’s in x;

head(b, x) is the number of leading b’s in x;

R(x, T) = n, if tail(0, x) > T and head(1, x) > T; and

R(x, T) = 0, otherwise.

Fitness(x, T) = \max(tail(0, x), head(1, x)) + R(x, T)

In [17]:
t_pct = .15
length = 50

def get_peaks_optimal(t_pct, length):
    left_size = math.ceil(t_pct * length) + 1
    right_size = length - left_size
    return length + right_size

get_peaks_optimal(t_pct, length)

91

In [21]:
fitness = mlrose.FourPeaks(t_pct=t_pct)
problem = mlrose.DiscreteOpt(length = length, fitness_fn = fitness, max_val = 2)
mlrose.genetic_alg(problem, curve=True, pop_size=200, max_attempts=100, mutation_prob=.7, hamming_factor=.1)

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]),
 91.0,
 array([[1.2000e+01, 4.0200e+02],
        [1.2000e+01, 6.0300e+02],
        [1.4000e+01, 8.0500e+02],
        [1.4000e+01, 1.0060e+03],
        [1.4000e+01, 1.2070e+03],
        [1.7000e+01, 1.4090e+03],
        [2.0000e+01, 1.6110e+03],
        [6.6000e+01, 1.8130e+03],
        [6.6000e+01, 2.0140e+03],
        [6.6000e+01, 2.2150e+03],
        [7.0000e+01, 2.4170e+03],
        [7.1000e+01, 2.6190e+03],
        [7.1000e+01, 2.8200e+03],
        [7.1000e+01, 3.0210e+03],
        [7.4000e+01, 3.2230e+03],
        [7.4000e+01, 3.4240e+03],
        [7.4000e+01, 3.6250e+03],
        [7.4000e+01, 3.8260e+03],
        [7.4000e+01, 4.0270e+03],
        [7.7000e+01, 4.2290e+03],
        [7.7000e+01, 4.4300e+03],
        [7.8000e+01, 4.6320e+03],
        [7.8000e+01, 4.8330e+03],
        [7.8000e+01, 5.0340e+03],
 

In [27]:
fitness = mlrose.FourPeaks(t_pct=t_pct)
problem = mlrose.DiscreteOpt(length = length, fitness_fn = fitness, max_val = 2)
mlrose.genetic_alg(problem, curve=True)

(array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 36.0,
 array([[  26.,  402.],
        [  26.,  603.],
        [  29.,  805.],
        [  29., 1006.],
        [  32., 1208.],
        [  32., 1409.],
        [  32., 1610.],
        [  32., 1811.],
        [  32., 2012.],
        [  33., 2214.],
        [  35., 2416.],
        [  35., 2617.],
        [  36., 2819.],
        [  36., 3020.],
        [  36., 3221.],
        [  36., 3422.],
        [  36., 3623.],
        [  36., 3824.],
        [  36., 4025.],
        [  36., 4226.],
        [  36., 4427.],
        [  36., 4628.],
        [  36., 4829.]]))

In [28]:
mlrose.simulated_annealing(problem, curve=True, max_attempts=200)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 20.0,
 array([[  3.,   2.],
        [  3.,   4.],
        [  3.,   5.],
        ...,
        [ 20., 640.],
        [ 20., 641.],
        [ 20., 642.]]))

In [25]:
mlrose.random_hill_climb(problem, curve=True)

(array([1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1]),
 3.0,
 array([[ 1., 71.],
        [ 1., 72.],
        [ 3., 74.],
        [ 3., 75.],
        [ 3., 76.],
        [ 3., 77.],
        [ 3., 78.],
        [ 3., 79.],
        [ 3., 80.],
        [ 3., 81.],
        [ 3., 82.],
        [ 3., 83.],
        [ 3., 84.]]))